apiVersion: v1
kind: Service
metadata:
  name: cinfo-mongodb
  labels:
    app: cinfo-mongodb
    service: cinfo-mongodb

spec:
  selector:
    app: cinfo-mongodb
  type: NodePort
  ports:
    - port: 27019
      targetPort: 27017
      nodePort: 30050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinfo-mongodb-v1
  labels:
    app: cinfo-mongodb
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinfo-mongodb
      version: v1
  template:
    metadata:
      labels:
        app: cinfo-mongodb
        version: v1
    spec:
      containers:
      - name: cinfo-mongodb
        image: docker.io/foroughsh/monogdb_collections_3:v1
        #imagePullPolicy: Never
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data-db
          mountPath: /data/db
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: data-db
        emptyDir: {}
---